### ISSUE TITLE
M-s, h fails

### ISSUE THREAD

**Issue by liwp** [mickeynp/discover.el#10]
I might be doing something wrong, but when I hit `M-s` followed by `h` (for highlighters) I get an error:

```
if: Wrong type argument: commandp, (discover-get-context-menu-command-name (quote isearch-highlight))
```

I can see that there is no `makey-key-mode-popup-isearch-highlight` defined in my environment. Should there be? A `makey-key-mode-popup-isearch` is defined.

I can execute

```
(commandp (intern (concat "makey-key-mode-popup-" (symbol-name 'isearch))))
```

which returns `t`.

And I can execute

```
(commandp (intern (concat "makey-key-mode-popup-" (symbol-name 'isearch-highlight))))
```

which returns `nil`.

But neither throws an error, so I don't understand what's going wrong with `M-s` `h`.

**Comment by mickeynp** [comment]
Hi liwp. I've just pushed a fix for this. Could you try it with the latest version of both makey and discover?

IF you're getting this through MELPA it might take a while for the new changes to percolate.

Thanks for the bug report.

**Comment by liwp** [comment]
@mickeynp thanks, that fixes my issue.
