### ISSUE TITLE
Rectangle commands not working on latest emacs

### ISSUE THREAD

**Issue by AdrieanKhisbe** [mickeynp/discover.el#13]
Activating Discover mode is currently breaking all the `C-x r` bindings (rectangles, registers and co) on latest emacs version.
This appeared when I went from `GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.6.4) of 2014-01-03 on peryton, modified by Debian` to `GNU Emacs 24.3.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.6.4) of 2014-01-28 on chindi01`.

(disabling  `(rectangles nil nil "C-x r")`  line ~ 367 prevent this problem to occur,  maybe it's related to an eventual change of behavior of keymaps chaining)

**Comment by mickeynp** [comment]
I cannot reproduce this against trunk Emacs (Emacs 24.4.50.1).

**Comment by AdrieanKhisbe** [comment]
Had to reinstall, and changed emacs version so cannot reproduce anymore. (had even totally forget about it), so closing :)

**Comment by ddoherty03** [comment]
I am seeing this same issue after upgrading from 23.3 to 24.4.  I have re-installed discover, but the problem persists.

**Comment by GregorZattler** [comment]
Still the case at least since emacs commit 22294ae511509ad86586eb5d054c95de38e87894 (2015-01-16).
