### ISSUE TITLE
Add support for help subcommands (C-h)

### ISSUE THREAD

**Issue by dakrone** [mickeynp/discover.el#4]
This is a feature request for adding a discover commands for C-h. I know it already supports popping up a buffer with commands using `?`, but discover support would be more visually pleasing.

**Comment by mickeynp** [comment]
I'm not too keen on overriding C-h as that is a fairly encompassing command that includes nested commands. Typing `C-x C-h` is a good example. My long-term goal is to update discover.el so it supports most of built-in Emacs - rendering the need for this feature redundant (I hope!)

If you have any particular areas of Emacs that warrants attention do feel free to say.

I have also updated the documentation and code to support third-party packages.

**Comment by dakrone** [comment]
Makes sense, thanks!
